internal/app/loophole/loophole.go

Removed emoji for Windows compatibility

---

cmd/root.go
go.mod
go.sum
internal/app/loophole/loophole.go
internal/app/loophole/models/Config.go

Closes #26 
I remembered I already had most of this written, only needed to change the writer to _colorableoutput_ to make it compatible with Windows. Tested and working on Windows and Ubuntu.

Initial QR feature added

---

internal/app/loophole/loophole.go
internal/pkg/client/client.go

Closes #18 
Closes https://github.com/loophole/api/issues/4

Handle 400 and 409 errors

---

internal/app/loophole/loophole.go

Closes #13 
For now a simple message asking for feedback as proposed, still needs an actual link as well

Added feedback message after termination of successful connection

---

internal/app/loophole/loophole.go

Longer Outage Reconnect fix

---

internal/app/loophole/loophole.go

Fixed misleading variable names inside handleClient

---

internal/app/loophole/loophole.go

Fixed the bug by saving the state of the terminal before entering the SSH key, to be restored in the close handler in case the user closes the application during the password entering phase.
Closes #53

Fixed terminal input staying invisible

---

internal/pkg/apiclient/apiclient.go

Since it might be frustrating just to be told to log in without knowing how when you're a new user, I added instructions on what command to use to accomplish that to the error msg

Added instructions on how to login to error msg

---

cmd/virtual-serve.go
internal/pkg/keys/keys.go

New SSH key flow

---

cmd/path.go
cmd/virtual-serve.go
go.mod
go.sum
internal/app/loophole/loophole.go
internal/app/loophole/models/RemoteEndpointSpecs.go
internal/pkg/httpserver/httpserver.go

Add basic-auth support

---

cmd/webdav.go
go.mod
internal/app/loophole/loophole.go
internal/app/loophole/models/ExposeDirectoryConfig.go
internal/app/loophole/models/ExposePortConfig.go
internal/app/loophole/models/ExposeWebdavConfig.go
internal/pkg/communication/communication.go
internal/pkg/httpserver/httpserver.go

WebDav support

---

cmd/webdav.go
go.mod
internal/app/loophole/loophole.go
internal/app/loophole/models/ExposeDirectoryConfig.go
internal/app/loophole/models/ExposePortConfig.go
internal/app/loophole/models/ExposeWebdavConfig.go
internal/pkg/communication/communication.go
internal/pkg/httpserver/httpserver.go
internal/pkg/urlmaker/urlmaker.go
internal/pkg/urlmaker/urlmaker_test.go

SSL certificate is fetched on startup

---

cmd/http.go
internal/app/loophole/loophole.go
internal/app/loophole/models/DisplayOptions.go
internal/pkg/httpserver/httpserver.go
internal/pkg/httpserver/proxyerrortemplate.go

Clsoes #30 
Now user will see this message:

Custom proxy error message

---

go.mod
go.sum
internal/pkg/communication/communication.go

Use halfblocks for smaller QR Codes

---

cmd/http.go
internal/app/loophole/loophole.go
internal/pkg/httpserver/httpserver.go

feat: enable --https flag for HTTPS servers

---

cmd/root.go
go.mod
go.sum
internal/app/loophole/loophole.go
internal/app/loophole/models/DisplayOptions.go
internal/pkg/apiclient/apiclient.go
internal/pkg/apiclient/apiclient_test.go

feat: Report update available

---

ui/desktop/src/components/form/BasicAuthSettings.tsx
ui/desktop/src/components/form/HostnameSettings.tsx
ui/desktop/src/components/form/LocalDirectorySettings.tsx
ui/desktop/src/components/form/LocalWebserverSettings.tsx
ui/desktop/src/features/validator/validators.ts
ui/desktop/src/pages/Directory.tsx
ui/desktop/src/pages/HTTP.tsx
ui/desktop/src/pages/WebDav.tsx

Part of #89 together with https://github.com/loophole/api/pull/12

Allow hostname to contain delimiters

---

cmd/virtual-serve.go
internal/pkg/closehandler/closehandler.go
internal/pkg/inpututil/inpututil.go

Closes #95 
Still want to clean it up a little before we merge it and haven't had time to test it properly yet, but the first commit should contain everything that is needed to fix the issue.

Fix input from pipe

---

cmd/http.go
internal/app/loophole/loophole.go
internal/app/loophole/models/Endpoint.go
internal/app/loophole/models/LocalHTTPEndpointSpecs.go
internal/pkg/httpserver/httpserver.go
internal/pkg/httpserver/tls_config.go
ui/desktop/src/components/form/LocalWebserverSettings.tsx
ui/desktop/src/features/validator/validators.ts
ui/desktop/src/interfaces/LocalHTTPEndpointSpecs.ts
ui/desktop/src/pages/HTTP.tsx

Support path while forwarding http server

---

internal/pkg/httpserver/httpserver.go
internal/pkg/httpserver/tls_config.go

Add forwarded headers

---

internal/pkg/httpserver/httpserver.go

Override host header with actual target host

---

cmd/virtual-serve.go
internal/app/loophole/loophole.go
internal/app/loophole/models/RemoteEndpointSpecs.go
internal/pkg/httpserver/httpserver.go
internal/pkg/httpserver/tls_config.go
internal/pkg/httpserver/tls_config_dev.go
ui/desktop/src/interfaces/RemoteEndpointSpecs.ts
ui/desktop/src/pages/Directory.tsx
ui/desktop/src/pages/HTTP.tsx
ui/desktop/src/pages/WebDav.tsx

Allow disabling old ciphers
